home/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name ='home'

urlpatterns = [
    path('about/', views.AboutView, name='about'),
    path('contact/', views.ContactView, name='contact'),
    path('elements/', views.ElementsView, name='elements'),
    path('', views.IndexView, name='index'),
    path('news/', views.NewsView, name='news'),
    path('service/', views.ServiceView, name='service'),
    ]

hosptalsam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path('user', include('user.urls')),
    path('chat/', include('message.urls')),

]
admin.site.index_title = "Clinika start up"
admin.site.site_header = "Clinica Admin"
admin.site.site_title = "Baravoo!!!"

message/urls.py
from django.urls import path
from . import views

app_name= 'message'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
    ]

user/urls.py
from django.urls import path


app_name = 'user'


urlpatterns = [
    # path('open/chat/', chat_room, name='chat_room'),
    # # path('chat/<int:recipient_id>/', chat_room, name='chat_room'),
]

message/models.py
from django.db import models

# Create your models here.

service/models.py
from django.db import models

class Clinic(models.Model):
    name = models.CharField(verbose_name="Poliklinika nomi", max_length=255)

    def __str__(self):
        return self.name

user/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models


class MyUserManager(BaseUserManager):
    """
    A custom user manager to deal with emails as unique identifiers for auth
    instead of usernames. The default that's used is "UserManager"
    """

    def create_user(self, username, password=None, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.is_active = True
        user.save()
        return user

    def _create_user(self, username, password=None, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        user = self.model(username=username, **extra_fields)
        user.is_active = True
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(username, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    USER_TYPE = (
        ('doctor_leader', 'Bosh shifokor'),
        ('doctor', 'Shifokor'),
        ('nurse', 'Hamshira'),
        ('citizen', 'Patsient'),
        ('admin', 'Admin'),
    )
    first_name = models.CharField(verbose_name='Ism', max_length=255, blank=True, null=True)
    last_name = models.CharField(verbose_name='Familiya', max_length=255, blank=True, null=True)
    email = models.EmailField(verbose_name='Pochta', unique=False, blank=True, null=True)
    username = models.CharField(verbose_name='username', max_length=255, unique=True)
    is_staff = models.BooleanField(verbose_name='Xodimlarning holati', default=False, )
    is_active = models.BooleanField(verbose_name='Faol', default=True, )
    birthday = models.DateField(verbose_name="Tug'ilgan kun",
                                null=True, blank=True)
    phone = models.CharField(verbose_name='Telefon raqami', max_length=255, null=True, blank=True)
    user_type = models.CharField(verbose_name='Foydalanuvchi turi', max_length=255, choices=USER_TYPE, default='nurse')
    clinic_leader = models.ForeignKey('service.Clinic', verbose_name='Qaysi poliklinika bosh shifokori',
                                     on_delete=models.SET_NULL, null=True, blank=True)
    # doctor = models.ForeignKey('user.', verbose_name='Qaysi sektor rahbari',
    #                            on_delete=models.SET_NULL, null=True, blank=True)

    USERNAME_FIELD = 'username'
    objects = MyUserManager()

    def __str__(self):
        return self.username

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_short_name(self):
        return self.first_name

    class Meta:
        verbose_name = 'Foydalanuvchi'
        verbose_name_plural = 'Foydalanuvchilar'

home/views.py
from django.shortcuts import render
from user.models import User


# Create your views here.

def IndexView(request):
    user = User.objects.all()
    print(user)
    return render(request, 'index.html', {'user': user})


def ContactView(request):
    return render(request, 'contact.html')


def ElementsView(request):
    return render(request, 'elements.html')


def AboutView(request):
    return render(request, 'about.html')


def NewsView(request):
    return render(request, 'news.html')


def ServiceView(request):
    return render(request, 'services.html')

message/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'chat/index.html', {})


def room(request, room_name):
    return render(request, 'chat/chatroom.html', {
        'room_name': room_name
    })

service/views.py
from django.shortcuts import render

# Create your views here.

user/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from .models import User
from .models import *

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>About us</title>
{% include 'add/head.html' %}
</head>
<body>

<div class="super_container">
	
	<!-- Header -->

	{% include 'add/header.html' %}
	
	<!-- Home -->

	<div class="home">
		<div class="home_background parallax-window" data-parallax="scroll" data-image-src="images/about.jpg" data-speed="0.8"></div>
		<div class="home_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="home_content">
							<div class="home_title">About <span>CareMed</span></div>
							<div class="breadcrumbs">
								<ul>
									<li><a href="#">Home</a></li>
									<li>About Caremed</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- About -->

	<div class="about">
		<div class="container">
			<div class="row">

				<!-- About Content -->
				<div class="col-lg-8">
					<div class="section_title"><h2>A great medical team to help your needs</h2></div>
					<div class="about_text">
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ante leo, finibus quis est ut, tempor tincidunt ipsum. Nam consequat semper sollicitudin. Aliquam nec dapibus massa. Pellen tesque in luctus ex. Praesent luctus erat sit amet tortor aliquam bibendum. Nulla ut molestie augue, scelerisque consectetur quam. Dolor sit amet, consectetur adipiscing elit. Cura bitur ante leo, finibus quis est ut, tempor tincidunt ipsum. Nam consequat semper sollicitudin. Aliquam nec dapibus massa. Pellentesque in luctus ex.</p>
						<p>Praesent luctus erat sit amet tortor aliquam bibendum. Nulla ut molestie augue, scelerisque consectetur quam. Dolor sit amet, consectetur adipiscing elit. Cura bitur ante leo, finibus quis est ut, tempor tincidunt ipsum. Nam consequat semper sollicitudin. Aliquam nec dapibus massa. Pellentesque in luctus ex.</p>
					</div>
					<div class="row loaders_container">
						<div class="col-md-3 loader_col">
							<!-- Loader -->
							<div class="loader" data-perc="0.75"><span>Hard Work</span></div>
						</div>
						<div class="col-md-3 loader_col">
							<!-- Loader -->
							<div class="loader" data-perc="0.95"><span>Passion</span></div>
						</div>
						<div class="col-md-3 loader_col">
							<!-- Loader -->
							<div class="loader" data-perc="0.75"><span>Hard Work</span></div>
						</div>
						<div class="col-md-3 loader_col">
							<!-- Loader -->
							<div class="loader" data-perc="0.95"><span>Passion</span></div>
						</div>
					</div>
					<div class="button about_button"><a href="#">read more</a></div>
				</div>

				<!-- Boxes -->
				<div class="col-lg-4 boxes_col">

					<!-- Box -->
					<div class="box working_hours">
						<div class="box_icon d-flex flex-column align-items-start justify-content-center"><div style="width:29px; height:29px;"><img src="images/alarm-clock.svg" alt=""></div></div>
						<div class="box_title">Working Hours</div>
						<div class="working_hours_list">
							<ul>
								<li class="d-flex flex-row align-items-center justify-content-start">
									<div>Monday – Friday</div>
									<div class="ml-auto">8.00 – 19.00</div>
								</li>
								<li class="d-flex flex-row align-items-center justify-content-start">
									<div>Saturday</div>
									<div class="ml-auto">9.30 – 17.00</div>
								</li>
								<li class="d-flex flex-row align-items-center justify-content-start">
									<div>Sunday</div>
									<div class="ml-auto">9.30 – 15.00</div>
								</li>
							</ul>
						</div>
					</div>

					<!-- Box -->
					<div class="box box_appointments">
						<div class="box_icon d-flex flex-column align-items-start justify-content-center"><div style="width: 29px; height:29px;"><img src="images/phone-call.svg" alt=""></div></div>
						<div class="box_title">Appointments</div>
						<div class="box_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ante leo, finibus quis est ut, tempor tincidunt ipsum. Nam cons equat semper sollicitudin.</div>
					</div>

					<!-- Box -->
					<div class="box box_emergency">
						<div class="box_icon d-flex flex-column align-items-start justify-content-center"><div style="width: 37px; height:37px; margin-left:-4px;"><img src="images/bell.svg" alt=""></div></div>
						<div class="box_title">Emergency Cases</div>
						<div class="box_phone">+56 273 45678 235</div>
						<div class="box_emergency_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ante leo.</div>
					</div>

				</div>
			</div>
		</div>
	</div>

	<!-- Testimonials -->

	<div class="testimonials">
		<div class="testimonials_background parallax-window" data-parallax="scroll" data-image-src="images/testimonials.jpg" data-speed="0.8"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="section_title section_title_light"><h2>Patient Testimonials</h2></div>
				</div>
			</div>
			<div class="row test_row">
				
				<!-- Testimonial -->
				<div class="col-lg-6 test_col">
					<div class="testimonial">
						<div class="test_icon d-flex flex-column align-items-center justify-content-center"><img src="images/quote.png" alt=""></div>
						<div class="test_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ante leo, finibus quis est ut, tempor tincidunt ipsum. Nam consequat semper sollicitudin. Aliquam nec dap ibus massa. Pellen tesque in luctus ex. Praesent luctus erat sit amet torto.</div>
						<div class="test_author d-flex flex-row align-items-center justify-content-start">
							<div class="test_author_image"><div><img src="images/test_1.jpg" alt=""></div></div>
							<div class="test_author_name"><a href="#">Claire Smith</a>, <span>Patient</span></div>
						</div>
					</div>
				</div>

				<!-- Testimonial -->
				<div class="col-lg-6 test_col">
					<div class="testimonial">
						<div class="test_icon d-flex flex-column align-items-center justify-content-center"><img src="images/quote.png" alt=""></div>
						<div class="test_text">Slor sit amet, consectetur adipiscing elit. Curabitur ante leo, finibus quis est ut, tempor tincidunt ipsum. Nam consequat semper sollicitudin. Aliquam nec dap ibus massa. Pellen tesque in luctus ex. Praesent luctus erat sit amet tortor aliquam bibendum.</div>
						<div class="test_author d-flex flex-row align-items-center justify-content-start">
							<div class="test_author_image"><div><img src="images/test_2.jpg" alt=""></div></div>
							<div class="test_author_name"><a href="#">Mick Williams</a>, <span>Patient</span></div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>

	<!-- Team -->

	<div class="team">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="section_title"><h2>Meet Our Medical Team</h2></div>
				</div>
			</div>
			<div class="row team_row">
				
				<!-- Team Member -->
				<div class="col-lg-3 team_col">
					<div class="team_member">
						<div class="team_member_image d-flex flex-column align-items-center justify-content-end"><img src="images/team_1.png" alt=""></div>
						<div class="team_member_info">
							<div class="team_member_name"><a href="#">Dr. Melissa Smith</a></div>
							<div class="team_member_title">Cardiologist</div>
						</div>
					</div>
				</div>

				<!-- Team Member -->
				<div class="col-lg-3 team_col">
					<div class="team_member">
						<div class="team_member_image d-flex flex-column align-items-center justify-content-end"><img src="images/team_2.png" alt=""></div>
						<div class="team_member_info">
							<div class="team_member_name"><a href="#">Dr. Josh Henderson</a></div>
							<div class="team_member_title">Plastic Surgeon</div>
						</div>
					</div>
				</div>

				<!-- Team Member -->
				<div class="col-lg-3 team_col">
					<div class="team_member">
						<div class="team_member_image d-flex flex-column align-items-center justify-content-end"><img src="images/team_3.png" alt=""></div>
						<div class="team_member_info">
							<div class="team_member_name"><a href="#">Dr. Christinne Jones</a></div>
							<div class="team_member_title">Pediatrist</div>
						</div>
					</div>
				</div>

				<!-- Team Member -->
				<div class="col-lg-3 team_col">
					<div class="team_member">
						<div class="team_member_image d-flex flex-column align-items-center justify-content-end"><img src="images/team_4.png" alt=""></div>
						<div class="team_member_info">
							<div class="team_member_name"><a href="#">Dr. William Stan</a></div>
							<div class="team_member_title">General Practicioner</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>

	<!-- Call to action -->

	<div class="cta">
		<div class="cta_background parallax-window" data-parallax="scroll" data-image-src="images/cta.jpg" data-speed="0.8"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="cta_content text-center">
						<h2>Need a personal health plan?</h2>
						<p>Duis massa massa, mollis vel ullamcorper quis, finibus et urna. Aliquam ac eleifend metus. Ut sollicitudin risus ex</p>
						<div class="button cta_button"><a href="#">request a plan</a></div>
					</div>
				</div>
			</div>
		</div>		
	</div>

	<!-- Footer -->
	{% include 'add/footer.html' %}
</div>
{% include 'add/script.html' %}

</body>
</html>

templates/add/footer.html
{% load static %}
<footer class="footer">
		<div class="footer_container">
			<div class="container">
				<div class="row">

					<!-- Footer - About -->
					<div class="col-lg-4 footer_col">
						<div class="footer_about">
							<div class="footer_logo_container">
								<a href="#" class="d-flex flex-column align-items-center justify-content-center">
									<div class="logo_content">
										<div class="logo d-flex flex-row align-items-center justify-content-center">
											<div class="logo_text">Care<span>Med</span></div>
											<div class="logo_box">+</div>
										</div>
										<div class="logo_sub">Health Care Center</div>
									</div>
								</a>
							</div>
							<div class="footer_about_text">
								<p>Lorem ipsum dolor sit amet, conse ctetur adipiscing elit. Curabitur ante leo, finibus quis est ut, tempor tincidunt ipsum.</p>
							</div>
							<ul class="footer_about_list">
								<li><div class="footer_about_icon"><img src="images/phone-call.svg" alt=""></div><span>+45 677 8993000 223</span></li>
								<li><div class="footer_about_icon"><img src="images/envelope.svg" alt=""></div><span>office@template.com</span></li>
								<li><div class="footer_about_icon"><img src="images/placeholder.svg" alt=""></div><span>Main Str. no 45-46, b3, 56832, Los Angeles, CA</span></li>
							</ul>
						</div>
					</div>

					<!-- Footer - Links -->
					<div class="col-lg-4 footer_col">
						<div class="footer_links footer_column">
							<div class="footer_title">Useful Links</div>
							<ul>
								<li><a href="#">Testimonials</a></li>
								<li><a href="#">FAQ</a></li>
								<li><a href="#">Apply for a Job</a></li>
								<li><a href="#">Terms & Conditions</a></li>
								<li><a href="#">Our Partners</a></li>
								<li><a href="#">Services</a></li>
								<li><a href="#">Free services</a></li>
								<li><a href="#">About us</a></li>
								<li><a href="#">News</a></li>
								<li><a href="#">Contact</a></li>
								<li><a href="#">Our Screening Program</a></li>
								<li><a href="#">FAQ</a></li>
							</ul>
						</div>
					</div>

					<!-- Footer - News -->
					<div class="col-lg-4 footer_col">
						<div class="footer_news footer_column">
							<div class="footer_title">Useful Links</div>
							<ul>
								<li>
									<div class="footer_news_title"><a href="news.html">Aliquam ac eleifend metus</a></div>
									<div class="footer_news_date">March 10, 2018</div>
								</li>
								<li>
									<div class="footer_news_title"><a href="news.html">Donec in libero sit amet mi vulputate</a></div>
									<div class="footer_news_date">March 10, 2018</div>
								</li>
								<li>
									<div class="footer_news_title"><a href="news.html">Aliquam ac eleifend metus</a></div>
									<div class="footer_news_date">March 10, 2018</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="copyright">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="copyright_content d-flex flex-lg-row flex-column align-items-lg-center justify-content-start">
							<div class="cr"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
							<div class="footer_social ml-lg-auto">
								<ul>
									<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
									<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
									<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
									<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
									<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>

templates/add/head.html
{% load static %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="CareMed demo project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/about.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/about_responsive.css' %}">

templates/add/header.html
{% load static %}

<header class="header trans_200">

      <!-- Top Bar -->
      <div class="top_bar">
          <div class="container">
              <div class="row">
                  <div class="col">
                      <div class="top_bar_content d-flex flex-row align-items-center justify-content-start">
                          <div class="top_bar_item"><a href="#">FAQ</a></div>
                          <div class="top_bar_item"><a href="#">Request an Appointment</a></div>
                          <div class="emergencies  d-flex flex-row align-items-center justify-content-start ml-auto">For Emergencies: +563 47558 623</div>
                      </div>

                  </div>
              </div>
          </div>
      </div>

      <!-- Header Content -->
      <div class="header_container">
          <div class="container">
              <div class="row">
                  <div class="col">
                      <div class="header_content d-flex flex-row align-items-center justify-content-start">
                          <nav class="main_nav ml-auto">
                              <ul>
                                  <li><a href="{% url 'home:index' %}">Home</a></li>
                                  <li><a href="{% url 'home:about' %}">About us</a></li>
                                  <li><a href="{% url 'home:service' %}">Services</a></li>
                                  <li><a href="{% url 'home:news' %}">News</a></li>
                                  <li><a href="{% url 'home:contact' %}">Contact</a></li>
                                  {% if user.is_authenticated %}
                                  <h1>MESSAGE</h1>
                                  <li><a href="{% url 'user:chat_room' user.username %}">Message</a></li><br>

                                  {% endif %}
                              </ul>
                          </nav>
                          <div class="hamburger ml-auto"><i class="fa fa-bars" aria-hidden="true"></i></div>
                      </div>
                  </div>
              </div>
          </div>
      </div>

      <!-- Logo -->
      <div class="logo_container_outer">
          <div class="container">
              <div class="row">
                  <div class="col">
                      <div class="logo_container">
                          <a href="#">
                              <div class="logo_content d-flex flex-column align-items-start justify-content-center">
                                  <div class="logo_line"></div>
                                  <div class="logo d-flex flex-row align-items-center justify-content-center">
                                      <div class="logo_text">Care<span>Med</span></div>
                                      <div class="logo_box">+</div>
                                  </div>
                                  <div class="logo_sub">Health Care Center</div>
                              </div>
                          </a>
                      </div>
                  </div>
              </div>
          </div>
      </div>

  </header>
<div class="menu_container menu_mm">

      <!-- Menu Close Button -->
      <div class="menu_close_container">
          <div class="menu_close"></div>
      </div>

      <!-- Menu Items -->
      <div class="menu_inner menu_mm">
          <div class="menu menu_mm">
              <ul class="menu_list menu_mm">
                  <li><a href="{% url 'home:index' %}">Home</a></li>
                  <li><a href="{% url 'home:about' %}">About us</a></li>
                  <li><a href="{% url 'home:service' %}">Services</a></li>
                  <li><a href="{% url 'home:news' %}">News</a></li>
                  <li><a href="{% url 'home:contact' %}">Contact</a></li>
              </ul>
          </div>
          <div class="menu_extra">
              <div class="menu_appointment"><a href="#">Request an Appointment</a></div>
              <div class="menu_emergencies">For Emergencies: +563 47558 623</div>
          </div>

      </div>

  </div>

templates/add/script.html
{% load static %}
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TweenMax.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TimelineMax.min.js' %}"></script>
<script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
<script src="{% static 'plugins/greensock/animation.gsap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/ScrollToPlugin.min.js' %}"></script>
<script src="{% static 'plugins/progressbar/progressbar.min.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'js/about.js' %}"></script>

templates/chat/chatroom.html
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>

<body>

    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-6">
                <form>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1" class="h4 pt-5">Chatroom</label>
                        <textarea class="form-control" id="chat-text" rows="10"></textarea><br>
                    </div>
                    <div class="form-group">
                        <input class="form-control" id="input" type="text"></br>
                    </div>
                    <input class="btn btn-secondary btn-lg btn-block" id="submit" type="button" value="Send">
                </form>
            </div>
        </div>
    </div>

    {{ request.user.username|json_script:"user_username" }}
    {{ room_name|json_script:"room-name" }}
    <script>
        const user_username = JSON.parse(document.getElementById('user_username').textContent);
        document.querySelector('#submit').onclick = function (e) {
            const messageInputDom = document.querySelector('#input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'username': user_username,
            }));
            messageInputDom.value = '';
        };




        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://' +
            window.location.host +
            '/ws/chat/' +
            roomName +
            '/'
        );

        chatSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            console.log(data)
            document.querySelector('#chat-text').value += (data.username + ': ' + data.message + '\n')
        }
    </script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
    </script>
</body>

</html>

templates/chat/index.html
<h1>chat</h1>